version: '3.8'
services:
  pgdb:
    image: postgres:15
    restart: always
    secrets:
      - pg_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
    volumes:
      - db:/var/lib/postgresql/data
      - ./Persian/database/schema.sql:/docker-entrypoint-initdb.d/001_schema.sql
      - ./Persian/database/accuweather.sql:/docker-entrypoint-initdb.d/010_accuweather.sql
      - ./Persian/database/cpm_table.sql:/docker-entrypoint-initdb.d/011_cpm_table.sql
      - ./Persian/database/form_names.sql:/docker-entrypoint-initdb.d/012_form_names.sql
      - ./Persian/database/forms.sql:/docker-entrypoint-initdb.d/013_forms.sql
      - ./Persian/database/item_names.sql:/docker-entrypoint-initdb.d/014_item_names.sql
      - ./Persian/database/move_names.sql:/docker-entrypoint-initdb.d/015_move_names.sql
      - ./Persian/database/moves.sql:/docker-entrypoint-initdb.d/016_moves.sql
      - ./Persian/database/movesets.sql:/docker-entrypoint-initdb.d/017_movesets.sql
      - ./Persian/database/pokedex.sql:/docker-entrypoint-initdb.d/018_pokedex.sql

      - ./Persian/database/research_tasks.sql:/docker-entrypoint-initdb.d/020_research_tasks.sql
      - ./Persian/database/task_names.sql:/docker-entrypoint-initdb.d/021_task_names.sql
      - ./Persian/database/team_names.sql:/docker-entrypoint-initdb.d/022_team_names.sql
      - ./Persian/database/teams.sql:/docker-entrypoint-initdb.d/023_teams.sql
      - ./Persian/database/type_chart.sql:/docker-entrypoint-initdb.d/024_type_chart.sql
      - ./Persian/database/types.sql:/docker-entrypoint-initdb.d/025_types.sql
      - ./Persian/database/weather_names.sql:/docker-entrypoint-initdb.d/026_weather_names.sql

      - ./Persian/database/pokemon.sql:/docker-entrypoint-initdb.d/100_pokemon.db
      - ./load_pokemon.sh:/docker-entrypoint-initdb.d/100_load_pokemon.sh
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  meowth:
    depends_on:
      - pgdb
    build:
      context: .
      dockerfile: ./Dockerfile
    secrets:
      - pg_password
      - bot_token
      - bot_master
      - gmaps_api_key
      - bot_coowners
    environment:
      BOT_TOKEN_FILE: /run/secrets/bot_token
      BOT_MASTER_FILE: /run/secrets/bot_master
      BOT_COOWNERS_FILE: /run/secrets/bot_coowners
      PG_HOSTNAME: pgdb
      PG_USERNAME: postgres
      PG_PASSWORD_FILE: /run/secrets/pg_password
      GMAPS_API_KEY_FILE: /run/secrets/gmaps_api_key

      PRELOAD_EXTENSIONS: "['raid','map','pkmn','research','rocket','wild','users','admin']"
volumes:
  db:
secrets:
  bot_token:
    file: secret_token.txt
  bot_master:
    file: secret_bot_master_user_id.txt
  bot_coowners:
    file: secret_bot_coowner_user_ids.txt
  pg_password:
    file: secret_postgres_password.txt
  gmaps_api_key:
    file: secret_gmaps_api_key.txt